### ISSUE TITLE
Pushing to GitLab with link_files fails under ruby 2

### ISSUE THREAD

**Issue by davidolrik** [git-commit-notifier/git-commit-notifier#212]
```bash
[djo@marklar test] $ git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 298 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Sending mail...
remote: /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:579:in `>=': comparison of String with Float failed (ArgumentError)
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:579:in `block in <class:DiffToHtml>'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:601:in `call'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:601:in `markup_commit_for_html'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:637:in `diff_for_commit'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:825:in `block in diff_for_branch'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:824:in `each'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:824:in `diff_for_branch'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/diff_to_html.rb:873:in `diff_between_revisions'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/commit_hook.rb:200:in `run'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/executor.rb:29:in `block in run!'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/executor.rb:27:in `each_line'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/lib/git_commit_notifier/executor.rb:27:in `run!'
remote: 	from /var/lib/gems/2.1.0/gems/git-commit-notifier-0.12.10/bin/git-commit-notifier:15:in `<top (required)>'
remote: 	from /usr/local/bin/git-commit-notifier:23:in `load'
remote: 	from /usr/local/bin/git-commit-notifier:23:in `<main>'
To git@git.dk.telia.net:xdjo/test.git
   9dd9ac7..3afeb5f  master -> master
```

**Comment by akzhan** [comment]
We used Runy 2.1 and Gitlab and have not reproduced this, btw.
